Kr01 connect to db
Marina-Yesakova/Bingo_CSD_412 pull request #13
Opened 2018-11-08 05:14 UTC by s-kyle-reed

Code to connect to a remote DB via TCP. It also creates a 'Words' class that is used to create a 'Words' table with Entity framework via migrations (these are done via powershell. These commands were found here: https://elanderson.net/2018/09/entity-framework-core-2-1-data-seeding)

2018-11-08 05:15 UTC, s-kyle-reed commented
I got these same conflicts on my local Git repo. Honestly I have no idea what they are.. :(.

2018-11-12 06:06 UTC, Marina-Yesakova commented on BingoTestClassLibrary/Class1.cs
> +namespace BingoTestClassLibrary
Why do we need this empty class?

2018-11-12 06:42 UTC, marina-berg requested changes
Please publish new iteration after removing bin, obj and vs files. 

1) figure out how to revert your commits, so that your changes are unstaged
2) "git checkout -- vs" 
3) "git checkout -- obj" 
4) "git checkout -- bin" 
5) "git pull origin master"
6) "git commit"
7) "git push"

It's important because the PR is very big and hard to review. Also, we don't have bin, obj and vs folders in the master anymore. And you will get rid of the conflicts that you have now in your PR. Thanks!

2018-11-12 06:42 UTC, Marina-Yesakova commented on BingoTestClassLibrary/Class1.cs
> +    }
Why do we need this empty class?

2018-11-26 01:15 UTC, s-kyle-reed commented
Closing this request to get over these blockers. Will create new pull request and apply changes there

2018-11-26 01:15 UTC, closed without merging

2018-11-26 18:48 UTC, Marina-Yesakova commented
Sounds good, looking forward to the new PR!

On Sun, Nov 25, 2018 at 5:15 PM s-kyle-reed <notifications@github.com>
wrote:

> Closed #13 <https://github.com/Marina-Yesakova/Bingo_CSD_412/pull/13>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Marina-Yesakova/Bingo_CSD_412/pull/13#event-1985659506>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOgEVilF5o8H2XSJE-0ZRlWvvzYtHq4Nks5uy0ClgaJpZM4YUAzE>
> .
>